// Generated by CoffeeScript 1.6.3
module.exports = function(url, callback) {
  var FeedParser, options, req, request, rss;
  FeedParser = require('feedparser');
  request = require('request');
  options = {
    normalize: false,
    addmeta: true,
    feedurl: url
  };
  rss = [];
  return req = request(url, function(err, res, body) {
    if (err || (res != null ? res.statusCode : void 0) !== 200) {
      return callback("request:" + url + ", Error:" + error);
    }
    return req.pipe(new FeedParser([options])).on('error', function(err) {
      return callback(err);
    }).on('readable', function() {
      var item, stream;
      stream = this;
      if (item = stream.read()) {
        return rss.push(item);
      }
    }).on('end', function() {
      if (rss.length === 0) {
        return callback('no articles');
      }
      return callback(null, rss);
    });
  });
};
