// Generated by CoffeeScript 1.6.3
module.exports = function(url, callback) {
  var FeedParser, options, request, rss;
  FeedParser = require('feedparser');
  request = require('request');
  options = {
    normalize: false,
    addmeta: true,
    feedurl: url
  };
  console.log("library loaded");
  rss = [];
  return request(url).pipe(new FeedParser([options])).on('error', function(error) {
    console.error("url request error");
    return console.error(error);
  }).on('readable', function() {
    var item, stream;
    stream = this;
    if (item = stream.read()) {
      console.log("" + item.title + " is added");
      return rss.push(item);
    }
  }).on('end', function() {
    console.log("finished. length: " + rss.length);
    return callback(rss);
  });
};
